apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntunode
  name: ubuntunode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntunode
  template:
    metadata:
      labels:
        app: ubuntunode
    spec:
      containers:
      - image: joeazhou/ubuntunode:latest
        name: ubuntunode        
        ports:
        - containerPort: 22
        - containerPort: 23
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: ubuntunode-service
spec:
  type: LoadBalancer
  selector:
    app: ubuntunode
  ports:
    - port: 22
      targetPort: 22 
      protocol: TCP
      name: tcp
    - port: 23
      targetPort: 23 
      protocol: TCP
      name: telnet
    - port: 80
      targetPort: 80 
      protocol: TCP
      name: http
