apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailhog
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - image: mailhog/mailhog
        name: mailhog        
        ports:
        - containerPort: 1025
        - containerPort: 8025
        
---

apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  type: LoadBalancer
  selector:
    app: mailhog
  ports:
    - port: 1025
      targetPort: 1025 
      protocol: TCP
      name: tcp
    - port: 8025
      targetPort: 8025 
      protocol: TCP
      name: http
